// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | OurheadSlice
  | OurServicesSlice
  | HomepageContactSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | Differentcontant3Slice
  | Differentcontant2Slice
  | DifferentcontantSlice
  | ServiceSlice
  | PageHeaderSlice
  | MakeUsDifferentSlice
  | ContactFormSlice
  | ContactInformationSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlices3Slice = MenuItemSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * gtag api key field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.gtag_api_key
   * - **Tab**: Google Analytics
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gtag_api_key: prismic.KeyTextField;

  /**
   * is enabled field in *Settings*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.is_enabled
   * - **Tab**: Google Analytics
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_enabled: prismic.BooleanField /**
   * recaptcha public key field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.recaptcha_public_key
   * - **Tab**: Recaptcha
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  recaptcha_public_key: prismic.KeyTextField;

  /**
   * recaptcha private key field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.recaptcha_private_key
   * - **Tab**: Recaptcha
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  recaptcha_private_key: prismic.KeyTextField /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices3[]
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<SettingsDocumentDataSlices3Slice> /**
   * address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  address: prismic.KeyTextField;

  /**
   * email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * contact email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_email: prismic.KeyTextField;

  /**
   * contact email password field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_email_password
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_email_password: prismic.KeyTextField;

  /**
   * email sender field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email_sender
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_sender: prismic.KeyTextField;

  /**
   * admin email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.admin_email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  admin_email: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type SubmenuDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Content for SubMenu documents
 */
interface SubmenuDocumentData {
  /**
   * Slice Zone field in *SubMenu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: submenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubmenuDocumentDataSlicesSlice>;
}

/**
 * SubMenu document from Prismic
 *
 * - **API ID**: `submenu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubmenuDocumentData>,
    "submenu",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | SettingsDocument
  | SubmenuDocument;

/**
 * Primary content in *ContactForm → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * title field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Default variation for ContactInformation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInformationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactInformation*
 */
type ContactInformationSliceVariation = ContactInformationSliceDefault;

/**
 * ContactInformation Shared Slice
 *
 * - **API ID**: `contact_information`
 * - **Description**: ContactInformation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInformationSlice = prismic.SharedSlice<
  "contact_information",
  ContactInformationSliceVariation
>;

/**
 * Primary content in *Whatmakeusdifferentone → Primary*
 */
export interface DifferentcontantSliceDefaultPrimary {
  /**
   * title field in *Whatmakeusdifferentone → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * sub_title field in *Whatmakeusdifferentone → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * img field in *Whatmakeusdifferentone → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant.primary.img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * ultitle field in *Whatmakeusdifferentone → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant.primary.ultitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ultitle: prismic.KeyTextField;

  /**
   * points field in *Whatmakeusdifferentone → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant.primary.points
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  points: prismic.RichTextField;
}

/**
 * Default variation for Whatmakeusdifferentone Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DifferentcontantSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DifferentcontantSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whatmakeusdifferentone*
 */
type DifferentcontantSliceVariation = DifferentcontantSliceDefault;

/**
 * Whatmakeusdifferentone Shared Slice
 *
 * - **API ID**: `differentcontant`
 * - **Description**: Differentcontant
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DifferentcontantSlice = prismic.SharedSlice<
  "differentcontant",
  DifferentcontantSliceVariation
>;

/**
 * Primary content in *Whatmakeusdifferenttwo → Primary*
 */
export interface Differentcontant2SliceDefaultPrimary {
  /**
   * ultitle field in *Whatmakeusdifferenttwo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant2.primary.ultitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ultitle: prismic.KeyTextField;

  /**
   * ulitem field in *Whatmakeusdifferenttwo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant2.primary.ulitem
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ulitem: prismic.RichTextField;

  /**
   * img field in *Whatmakeusdifferenttwo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant2.primary.img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * subtitle field in *Whatmakeusdifferenttwo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant2.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * description field in *Whatmakeusdifferenttwo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Whatmakeusdifferenttwo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Differentcontant2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Differentcontant2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whatmakeusdifferenttwo*
 */
type Differentcontant2SliceVariation = Differentcontant2SliceDefault;

/**
 * Whatmakeusdifferenttwo Shared Slice
 *
 * - **API ID**: `differentcontant2`
 * - **Description**: Differentcontant2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Differentcontant2Slice = prismic.SharedSlice<
  "differentcontant2",
  Differentcontant2SliceVariation
>;

/**
 * Primary content in *Whatmakeusdifferentthree → Primary*
 */
export interface Differentcontant3SliceDefaultPrimary {
  /**
   * img field in *Whatmakeusdifferentthree → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant3.primary.img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * title field in *Whatmakeusdifferentthree → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant3.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * sub_title field in *Whatmakeusdifferentthree → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: differentcontant3.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;
}

/**
 * Default variation for Whatmakeusdifferentthree Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Differentcontant3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Differentcontant3SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whatmakeusdifferentthree*
 */
type Differentcontant3SliceVariation = Differentcontant3SliceDefault;

/**
 * Whatmakeusdifferentthree Shared Slice
 *
 * - **API ID**: `differentcontant3`
 * - **Description**: Differentcontant3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Differentcontant3Slice = prismic.SharedSlice<
  "differentcontant3",
  Differentcontant3SliceVariation
>;

/**
 * Primary content in *HomepageContact → Primary*
 */
export interface HomepageContactSliceDefaultPrimary {
  /**
   * title green field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.title_green
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_green: prismic.KeyTextField;

  /**
   * title white 1 field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.title_white_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_white_1: prismic.KeyTextField;

  /**
   * title yellow field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.title_yellow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_yellow: prismic.KeyTextField;

  /**
   * title white 2 field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.title_white_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_white_2: prismic.KeyTextField;

  /**
   * title white 3 field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.title_white_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_white_3: prismic.KeyTextField;

  /**
   * button text field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * form title field in *HomepageContact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.form_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_title: prismic.KeyTextField;

  /**
   * desktop background field in *HomepageContact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.desktop_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  desktop_background: prismic.ImageField<never>;

  /**
   * mobile background field in *HomepageContact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.mobile_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_background: prismic.ImageField<never>;

  /**
   * description field in *HomepageContact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * button link field in *HomepageContact → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_contact.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for HomepageContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomepageContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomepageContact*
 */
type HomepageContactSliceVariation = HomepageContactSliceDefault;

/**
 * HomepageContact Shared Slice
 *
 * - **API ID**: `homepage_contact`
 * - **Description**: HomepageContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageContactSlice = prismic.SharedSlice<
  "homepage_contact",
  HomepageContactSliceVariation
>;

/**
 * Primary content in *MakeUsDifferent → Primary*
 */
export interface MakeUsDifferentSliceDefaultPrimary {
  /**
   * title field in *MakeUsDifferent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: make_us_different.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *MakeUsDifferent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: make_us_different.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *MakeUsDifferent → Items*
 */
export interface MakeUsDifferentSliceDefaultItem {
  /**
   * topic field in *MakeUsDifferent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: make_us_different.items[].topic
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  topic: prismic.RichTextField;

  /**
   * explanation field in *MakeUsDifferent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: make_us_different.items[].explanation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  explanation: prismic.RichTextField;
}

/**
 * Default variation for MakeUsDifferent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MakeUsDifferentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MakeUsDifferentSliceDefaultPrimary>,
  Simplify<MakeUsDifferentSliceDefaultItem>
>;

/**
 * Slice variation for *MakeUsDifferent*
 */
type MakeUsDifferentSliceVariation = MakeUsDifferentSliceDefault;

/**
 * MakeUsDifferent Shared Slice
 *
 * - **API ID**: `make_us_different`
 * - **Description**: MakeUsDifferent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MakeUsDifferentSlice = prismic.SharedSlice<
  "make_us_different",
  MakeUsDifferentSliceVariation
>;

/**
 * Primary content in *MenuItem → Items*
 */
export interface MenuItemSliceDefaultItem {
  /**
   * label field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *MenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MenuItemSliceDefaultItem>
>;

/**
 * Primary content in *MenuItem → Items*
 */
export interface MenuItemSliceWithSubMenuItem {
  /**
   * label field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * submenu field in *MenuItem → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].submenu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu: prismic.ContentRelationshipField;
}

/**
 * WithSubMenu variation for MenuItem Slice
 *
 * - **API ID**: `withSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithSubMenu = prismic.SharedSliceVariation<
  "withSubMenu",
  Record<string, never>,
  Simplify<MenuItemSliceWithSubMenuItem>
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault | MenuItemSliceWithSubMenu;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *OurServices → Primary*
 */
export interface OurServicesSliceDefaultPrimary {
  /**
   * bgone field in *OurServices → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.bgone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgone: prismic.ImageField<never>;

  /**
   * bgtwo field in *OurServices → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.bgtwo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgtwo: prismic.ImageField<never>;
}

/**
 * Primary content in *OurServices → Items*
 */
export interface OurServicesSliceDefaultItem {
  /**
   * imgs field in *OurServices → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].imgs
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imgs: prismic.ImageField<never>;

  /**
   * title field in *OurServices → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * sub_title field in *OurServices → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * description field in *OurServices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * buttonname field in *OurServices → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].buttonname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonname: prismic.KeyTextField;

  /**
   * Btn field in *OurServices → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].btn
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn: prismic.LinkField;
}

/**
 * Default variation for OurServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurServicesSliceDefaultPrimary>,
  Simplify<OurServicesSliceDefaultItem>
>;

/**
 * Slice variation for *OurServices*
 */
type OurServicesSliceVariation = OurServicesSliceDefault;

/**
 * OurServices Shared Slice
 *
 * - **API ID**: `our_services`
 * - **Description**: OurServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSlice = prismic.SharedSlice<
  "our_services",
  OurServicesSliceVariation
>;

/**
 * Primary content in *Ourhead → Primary*
 */
export interface OurheadSliceDefaultPrimary {
  /**
   * Our Services field in *Ourhead → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourhead.primary.our_services
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  our_services: prismic.KeyTextField;
}

/**
 * Default variation for Ourhead Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurheadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurheadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ourhead*
 */
type OurheadSliceVariation = OurheadSliceDefault;

/**
 * Ourhead Shared Slice
 *
 * - **API ID**: `ourhead`
 * - **Description**: Ourhead
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurheadSlice = prismic.SharedSlice<
  "ourhead",
  OurheadSliceVariation
>;

/**
 * Primary content in *PageHeader → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * title field in *PageHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * desktop background field in *PageHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.desktop_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  desktop_background: prismic.ImageField<never>;

  /**
   * mobile background field in *PageHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.mobile_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_background: prismic.ImageField<never>;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Primary content in *Service → Items*
 */
export interface ServiceSliceDefaultItem {
  /**
   * banner field in *Service → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.items[].banner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * title field in *Service → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Service → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ServiceSliceDefaultItem>
>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation = ServiceSliceDefault;

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<
  "service",
  ServiceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlices3Slice,
      SubmenuDocument,
      SubmenuDocumentData,
      SubmenuDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactInformationSlice,
      ContactInformationSliceVariation,
      ContactInformationSliceDefault,
      DifferentcontantSlice,
      DifferentcontantSliceDefaultPrimary,
      DifferentcontantSliceVariation,
      DifferentcontantSliceDefault,
      Differentcontant2Slice,
      Differentcontant2SliceDefaultPrimary,
      Differentcontant2SliceVariation,
      Differentcontant2SliceDefault,
      Differentcontant3Slice,
      Differentcontant3SliceDefaultPrimary,
      Differentcontant3SliceVariation,
      Differentcontant3SliceDefault,
      HomepageContactSlice,
      HomepageContactSliceDefaultPrimary,
      HomepageContactSliceVariation,
      HomepageContactSliceDefault,
      MakeUsDifferentSlice,
      MakeUsDifferentSliceDefaultPrimary,
      MakeUsDifferentSliceDefaultItem,
      MakeUsDifferentSliceVariation,
      MakeUsDifferentSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultItem,
      MenuItemSliceWithSubMenuItem,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceWithSubMenu,
      OurServicesSlice,
      OurServicesSliceDefaultPrimary,
      OurServicesSliceDefaultItem,
      OurServicesSliceVariation,
      OurServicesSliceDefault,
      OurheadSlice,
      OurheadSliceDefaultPrimary,
      OurheadSliceVariation,
      OurheadSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      ServiceSlice,
      ServiceSliceDefaultItem,
      ServiceSliceVariation,
      ServiceSliceDefault,
    };
  }
}
