// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  contact_information: dynamic(() => import("./ContactInformation")),
  differentcontant: dynamic(() => import("./Whatmakeusdifferentone")),
  differentcontant2: dynamic(() => import("./Whatmakeusdifferenttwo")),
  differentcontant3: dynamic(() => import("./Whatmakeusdifferentthree")),
  homepage_contact: dynamic(() => import("./HomepageContact")),
  make_us_different: dynamic(() => import("./MakeUsDifferent")),
  menu_item: dynamic(() => import("./MenuItem")),
  our_services: dynamic(() => import("./OurServices")),
  ourhead: dynamic(() => import("./Ourhead")),
  page_header: dynamic(() => import("./PageHeader")),
  service: dynamic(() => import("./Service")),
};
